# -*- coding: utf-8 -*-
"""Копия блокнота "new_collab"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bggwMIpbrRuiGu6cZwI1GjYZlv0hY3m7
"""

df <- read.csv("adult1.csv")
head(df)

df <- read.csv("howpop_train.csv")
head(df)

"""**1. Сколько мужчин и женщин (признак sex) представлено в этом наборе данных?**"""

table(df$sex)

"""**2. Каков средний возраст (признак age) женщин?**"""

mean(df[df['sex'] == " Female", "age"])

"""**3. Какова доля граждан Германии (признак native-country)?**"""

mean(df["native.country"] == " Germany")

"""*4-5. Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак *salary) и тех, кто получает менее 50K в год? **"""

mean(df[df['salary'] == " >50K", "age"])
sd(df[df['salary'] == " >50K", "age"])
mean(df[df['salary'] == " <=50K", "age"])
sd(df[df['salary'] == " <=50K", "age"])

"""**6. Правда ли, что люди, которые получают больше 50k, имеют как минимум высшее образование? (признак education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters или Doctorate)**"""

colnames <- df$education == " Bachelors" | df$education == " Prof-school" | df$education == " Assoc-acdm" | df$education == " Assoc-voc" | df$education == " Masters" | df$education == " Doctorate"

addmargins(table(df$salary, colnames))

"""**7. Выведите статистику возраста для каждой расы (признак race) и каждого пола. Используйте groupby и describe. Найдите таким образом максимальный возраст мужчин расы Amer-Indian-Eskimo.**"""

tapply(X = df$age, INDEX = list(df$sex, df$race), FUN = mean)

"""**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак marital-status)? Женатыми считаем тех, у кого marital-status начинается с Married (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**"""

i <- (df$marital.status == " Married-civ-spouse" | df$marital.status == " Married-spouse-absent" | df$marital.status == " Married-AF-spouse") & (df$sex == " Male")

addmargins(table(df$salary, i))

j <- (df$marital.status == " Divorced" | df$marital.status == " Widowed" | df$marital.status == " Separated" | df$marital.status == " Never-married") & (df$sex == " Male")

addmargins(table(df$salary, j))

"""**9. Какое максимальное число часов человек работает в неделю (признак hours-per-week)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**"""

i <- sum(df$hours.per.week == max(df$hours.per.week) & df$salary == " >50K")
i * 100 / sum(df$hours.per.week == max(df$hours.per.week))

"""**10. Посчитайте среднее время работы (hours-per-week) зарабатывающих мало и много (salary) для каждой страны (native-country).**"""

print(tapply(X = df$hours.per.week, INDEX = list(df$salary, df$native.country), FUN = mean))

"""## 1\. В каком месяце (и какого года) было больше всего публикаций?

* март 2016
* март 2015
* апрель 2015
* апрель 2016
"""

library(data.table)
library(dplyr)
library(lubridate)
data_set <- as_tibble(df)
data_set$published <- lubridate::ymd_hms(data_set$published)
data_set$published <- as.POSIXct(data_set$published, format = "%Y-%m-%d %H:%M:%S")
data_set$published <- strftime(data_set$published, format="%Y-%m")

march_2016 <- nrow(subset(data_set, published == "2016-03" ))
april_2016 <-  nrow(subset(data_set, published == "2016-04" ))

march_2015 <- nrow(subset(data_set, published == "2015-03" ))
april_2015 <- nrow(subset(data_set, published == "2015-04" ))


matrix_total <- cbind(march_2015,march_2016,april_2016,april_2015)
head(matrix_total)
barplot(matrix_total)

"""## 2\. Проанализируйте публикации в месяце из предыдущего вопроса

Выберите один или несколько вариантов:

* Один или несколько дней сильно выделяются из общей картины
* На хабре _всегда_ больше статей, чем на гиктаймсе
* По субботам на гиктаймс и на хабрахабр публикуют примерно одинаковое число статей

Подсказки: постройте график зависимости числа публикаций от дня; используйте параметр `hue`; не заморачивайтесь сильно с ответами и не ищите скрытого смысла :)
"""

library(dplyr)
library(lubridate)

df1 <- as_tibble(df)
df1$published <- lubridate::ymd_hms(df1$published)
df1$published <- as.POSIXct(df1$published, format = "%Y-%m-%d %H:%M:%S")
df1$published <- strftime(df1$published, format="%Y-%m")
df_habr<- nrow(subset(df1, published == "2015-03" & domain == "habrahabr.ru" ))
df_geek<- nrow(subset(df1, published == "2015-03" & domain == "geektimes.ru" ))
habr <- c(df_habr)
geektimes <- c(df_geek)
final2 <- cbind(habr,geektimes)
barplot(final2)
head(final2)

"""## 4\. Кого из топ-20 авторов чаще всего минусуют?

* @Mordatyj
* @Mithgol
* @alizar
* @ilya42

"""

library(dplyr)

df2 <- as_tibble(df)

Mordatyj <- filter(df2, df2$author == "@Mordatyj" )
vec_mor <- Mordatyj$votes_minus
sum_vec_mor <- sum(Mordatyj[, "votes_minus"], na.rm = TRUE)


Mithgol <- filter(df2, df2$author == "@Mithgol")
vec_mit <- Mithgol$votes_minus
sum_vec_mit <- sum(Mithgol[, "votes_minus"], na.rm = TRUE)

alizar_dat <- filter(df2, df2$author == "@alizar")
vec_ali <- alizar_dat$votes_minus
sum_vec_ali <- sum(alizar_dat[, "votes_minus"], na.rm = TRUE)

ilya42_dat <- filter(df2, df2$author == "@ilya42")
vec_ily <- ilya42_dat$votes_minus
sum_vec_ily <- sum(ilya42_dat[, "votes_minus"], na.rm = TRUE)


mithgol <- c(sum_vec_mit)
mordatyj <- c(sum_vec_mor)
ilya42 <- c(sum_vec_ily)
alizar <- c(sum_vec_ali)

final3 <- cbind(mithgol,mordatyj,ilya42,alizar)

head(final3)
barplot(final3)

library(dplyr)
library(lubridate)
library(ggplot2)
data4 <- as_tibble(df)

data_saved <- data4 %>% mutate(hour = hour(ymd_hms(published))) %>% group_by(hour) %>% summarise(comments = sum(comments, na.rm = TRUE), views = sum(views, na.rm = TRUE) )

data_saved[with(data_saved,  order(data_saved[,3],data_saved[,2])),]


ggplot(data_saved, aes(x=hour,y=comments)) + geom_col()
ggplot(data_saved, aes(x=hour,y=views)) +geom_col()

"""## 5\. Сравните субботы и понедельники

Правда ли, что по субботам авторы пишут в основном днём, а по понедельникам — в основном вечером?

"""

library(lubridate)
data_new <- as_tibble(df)
week_days<- wday(as.Date(data_new$published,"%Y-%m-%d %H:%M:%S"), label=TRUE,abbr=FALSE)

data_new$day <- week_days
data_new$published <- lubridate::ymd_hms(data_new$published)
data_new$published <- as.POSIXct(data_new$published, format = "%Y-%m-%d %H:%M:%S")
data_new$published <- strftime(data_new$published, format="%H")
monday_day<- nrow(subset(data_new, published >= 12 & published <= 18 & day == "Monday" ))
monday_evening <- nrow(subset(data_new, published >= 19 & published <= 22 & day == "Monday"))


saturday_day <- nrow(subset(data_new, published >= 12 & published <= 18 & day == "Saturday" ))
saturday_evening <- nrow(subset(data_new, published >= 19 & published <= 22 & day == "Saturday" ))

matrix_final <- cbind(monday_day,monday_evening,saturday_day,saturday_evening)
head(matrix_final)

barplot(matrix_final)